// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPantryBackend.Data;

#nullable disable

namespace ModernPantryBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221016113611_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModernPantryBackend.Models.SecondTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecondTestModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "N1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "N2"
                        });
                });

            modelBuilder.Entity("ModernPantryBackend.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondTestModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecondTestModelId");

                    b.ToTable("TestModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T1",
                            SecondTestModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "T2",
                            SecondTestModelId = 2
                        });
                });

            modelBuilder.Entity("ModernPantryBackend.Models.TestModel", b =>
                {
                    b.HasOne("ModernPantryBackend.Models.SecondTestModel", "SecondTestModel")
                        .WithMany()
                        .HasForeignKey("SecondTestModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SecondTestModel");
                });
#pragma warning restore 612, 618
        }
    }
}
